### ISSUE TITLE
Drummer community

### ISSUE THREAD

**Issue by alexjj** [scripting/drummerRFC#13]
@andysylvester created [Old School Drummers Reading List](http://oldschooldrummers.andysylvester.com/) which is an opt-in river of drummer blogs. He adds new people who request to be added and I enjoy finding new blogs to read. However, it may not be that widely known.

Whilst self-hosting is possible I suspect virtually all drummer blogs are hosted via Dave, and therefore there's a list of all drummer blogs. It be great if this list was public and accessible. Perhaps a new verb or opml file etc. Then others can discover new blogs or aggregate into a river etc.

**Comment by scripting** [comment]
@alexjj -- of course i've thought about this, and decided not to do it. i've been down this road many times, and it never ends well. 

also this isn't really a proper use for the rfc space. you could have sent me a private email about this, since you're only asking one person for something, there's no reason to broadcast the request, or the link to Andy's service.

so i would appreciate it if you deleted the question.
