### ISSUE TITLE
OPML Evangelism thoughts

### ISSUE THREAD

**Issue by jessegrosjean** [scripting/drummerRFC#27]
I'll start off by saying I'm not really the one to do this :), but since @scripting is already doing this work why note add a little more?

I think OPML could become more popular if it was clear to users and developers how it can help them. Since the point of using a standard is that you can share data between apps, I think a good start would be to create a place on [org.opm](http://opml.org) listing compatible apps. And better yet include some details on how they are compatible, since OPML compatible can mean many different things.

I'm starting such a [list here](https://bikeguide.hogbaysoftware.com/opml-compatible-apps), but I think it would make more sense to host this sort of list on http://opml.org. 

@scripting you mentioned on twitter you are in process of cleaning up your sites. It might be useful to change the hosting of that site to something like https://www.gitbook.com. The benefit would be that then the files are just in a git repo, and people can easily make pull request to edit the site (for example if they wish to add an OPML compatible app).

**Comment by scripting** [comment]
I'm glad you're building on OPML, but this isn't what I was working on now, and I can't turn my attention here. I agree we should have a list of compatible applications. Since you've started the list, please continue to manage it, and here's an idea -- publish it as OPML and I will be able to include it in the opml.org site. 

All those files in the site are OPML. If you click on the XML icon in the upper right corner of each page, you'll get the [OPML version](http://opml.org/?format=opml) of the page, so you can see how it works. 

The same is true for all the Drummer docs, they're all OPML files being rendered through a simple filter. 

I can have it serve a page from your site, I think. I haven't done it yet, but it should be possible.

**Comment by jessegrosjean** [comment]
That sounds reasonable. I'm going to set myself a reminder and come back to this issue in two months. Hopefully the OPML apps page will grow between now and then, and I don't want to deal with syncing too many changes to the OPML file.

**Comment by scripting** [comment]
You don’t use your outliner to write pages like that?

**Comment by jessegrosjean** [comment]
No, I like gitbook for generating user guide. It provides a nice clean and standard look with minimal extra effort on my part. My outliner use is more "surface for thinking and maybe some lists", Bike is really good at that, but it isn't really suitable for this sort of authoring. At least not without some extra effort which I'm avoiding for now.

**Comment by scripting** [comment]
That’s kind of how I feel about the todo list you gave me. I agree fully that having a list of apps on opml.org site is good. But changing everything about hiw I manage my sites isn’t in the cards. OPML is one of my major priorities, but not the only one. 😀

**Comment by scripting** [comment]
I just took a bike ride and thought a bit about this -- I don't mind transcribing the list you have right now, and doing updates as people post new items, if they do, in this thread (I'll put a note on the site).

I've done that before with the XML-RPC and SOAP developer websites many years ago. It's not too much of a burden.

But it's up to you, and it's totally okay if you want to keep the list on your site. But I'm ready to do the manual work now if you're ok with it.

**Comment by jessegrosjean** [comment]
Yes, please transcribe the list as you see fit. I think opml website is the correct place for an OPML compatible app list. I will link to that page from my user's guide.

I think I will continue to update the list in my guide as well, but instead of trying to be an "official" list I can make it a bit more Bike centric, discussing how Bike specifically can integrate with other apps. Seem reasonable?

**Comment by jessegrosjean** [comment]
@scripting Responding to your twitter comment here, more space.

> But both belong in your first category, they read and write OPML files, it's their native format. 

Of course this is true, but it's tricky, because from a Bike user's perspective you still have to import/export since it's a web app.

I did originally say "this is the best level of support, etc", but I have changed that text to be more descriptive. (note that the Bike Guide website seems to cache heavily, you might need to hard refresh your browser to see update).

I think this is a good argument for having a more official list on opml.org, my list is in the Bike users guide and so presented from that view.

I also think maybe my presentation categories are not super helpful. Better might be a flat list of apps along with a paragraph description of the OPML support provided by each app. I do think it's useful to say exactly how OPML is supported.

**Comment by jessegrosjean** [comment]
I've removed the categories and changed my list to be a bit more Bike centric. Let me know when your list is up and I'll link to it.

**Comment by scripting** [comment]
I understand you wrote the list from a Bike user's perspective. But it is a little more complicated since Drummer is available as a desktop app, and there you have the OPML files on your local hard drive, no need to download anything. 

I have transcribed the list, and set up a process for making suggestions and reporting problems. 

http://opml.org/compatibleApps.opml

Please let me know if you spot any problems.

And thanks for getting this started. If I had done it before it would have felt like pissing in the wind. But when there are two of us working on this, that's enough to get something going, hopefully. :-)

**Comment by jessegrosjean** [comment]
Thanks for taking this up. I've linked to the list and updated Drummers description ... I had quickly tried electron version, but thought it was just wrapping website. Local files, nice! The list looks good, though it's missing OutlineEdit which I just recently added.
